name: test-action

# run this on push to any branch and creation of pull-requests
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show environment variables
        run:
          echo Hi!
        env:
          PUSHER_EMAIL: ${{ github.event.pusher.email }}
          PR_USER_EMAIL: ${{ github.event.pull_request.user.email }}
          WORKFLOW: ${{ github.event.workflow }}
          WORKFLOW_DISPATCH: ${{ github.event.workflow_dispatch.sender }}
