name: test-action

# run this on push to any branch and creation of pull-requests
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show environment variables
        run:
          echo Hi!
        env:
          PUSHER_EMAIL: ${{ github.event.pusher.email }}
          PR_ACTION: ${{ github.event.pull_request.action }}
          PR_USER: ${{ github.event.pull_request.user.name }}
          WORKFLOW_RUN: ${{ github.event.workflow_run.actor.email }}
